#!/usr/bin/env python3
"""Generate keysmith-core/src/keycodes.rs from QMK's quantum/keycodes.h.

The table is generated rather than hand-written so it cannot drift from the
firmware, and committed so a normal build needs no QMK checkout.

Usage: tools/generate-keycodes.py <path-to-qmk> > crates/keysmith-core/src/keycodes.rs
"""
import re
import sys

qmk = sys.argv[1]
source = open(f"{qmk}/quantum/keycodes.h").read()

direct = {}
aliases = {}
for line in source.splitlines():
    line = line.split("//")[0].strip()
    m = re.match(r"^([A-Z][A-Z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+),?$", line)
    if m:
        direct[m.group(1)] = int(m.group(2), 16)
        continue
    m = re.match(r"^([A-Z][A-Z0-9_]*)\s*=\s*([A-Z][A-Z0-9_]*),?$", line)
    if m:
        aliases[m.group(1)] = m.group(2)

# Resolve aliases, tolerating chains.
for name, target in list(aliases.items()):
    seen = set()
    while target in aliases and target not in seen:
        seen.add(target)
        target = aliases[target]
    if target in direct:
        direct[name] = direct[target]

# Range sentinels are not keycodes and would otherwise win the display vote for
# values like 0x0100 that no real key uses.
names = {n: v for n, v in direct.items() if not n.endswith("_MAX")}

def preference(name):
    # A KC_ name is what a person writes; otherwise the shortest alias reads
    # best (UG_VALU over QK_UNDERGLOW_VALUE_UP).
    return (not name.startswith("KC_"), len(name), name)

display = {}
for name, value in names.items():
    if value not in display or preference(name) < preference(display[value]):
        display[value] = name

print("// Copyright 2026 Kartios")
print("// SPDX-License-Identifier: MIT")
print("//")
print("// @generated by tools/generate-keycodes.py from QMK quantum/keycodes.h.")
print("// Do not edit by hand; re-run the generator against a QMK checkout instead.")
print()
print("/// Every known keycode name and its value, sorted by name for binary search.")
print("pub static BY_NAME: &[(&str, u16)] = &[")
for name in sorted(names):
    print(f'    ("{name}", 0x{names[name]:04x}),')
print("];")
print()
print("/// One preferred display name per value, sorted by value for binary search.")
print("pub static BY_VALUE: &[(u16, &str)] = &[")
for value in sorted(display):
    print(f'    (0x{value:04x}, "{display[value]}"),')
print("];")
